# Generated by Django 5.1.2 on 2024-10-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FurnitureApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Quantity', models.IntegerField(blank=True, null=True)),
                ('Product_MRP', models.IntegerField(blank=True, null=True)),
                ('Product_Description', models.TextField(blank=True, max_length=300, null=True)),
                ('Product_Country', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Mfd', models.CharField(blank=True, max_length=100, null=True)),
                ('Product_Image1', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('Product_Image2', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('Product_Image3', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
    ]
