# Generated by Django 5.1.2 on 2024-10-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Signup_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Signup_Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Signup_Mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('Signup_Password', models.CharField(blank=True, max_length=100, null=True)),
                ('Signup_ConfirmPassword', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
