# Generated by Django 5.1.2 on 2024-10-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_signupdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigninDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Signin_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Signin_Password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
