# Generated by Django 5.1.2 on 2024-11-10 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_alter_cartdb_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SigninDB',
        ),
    ]
