# Generated by Django 5.1.2 on 2024-11-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_delete_signindb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdb',
            name='Total_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
